### PR TITLE
Test and document Config

### LINKED ISSUE #204: Improve `Config` ergonomy
Currently we are missing all `.require*` methods and the `.get*` methods return `Output[A]` and this results in silently ignoring missing keys with an empty output.

We might want to change the current behaviour to:
- `.get*` returning `Output[Option[A]]`
- `.require*` returning `Output[A]` with an error

The error content should be identical to the [reference implementation](https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/config.ts#L524):
```typescript
/**
 * ConfigMissingError is used when a configuration value is completely missing.
 */
class ConfigMissingError extends RunError {
    constructor(public key: string, public secret: boolean) {
        super(
            `Missing required configuration variable '${key}'\n` +
                `\tplease set a value using the command \`pulumi config set${
                    secret ? " --secret " : " "
                }${key} <value>\``,
        );
    }
}
```

Also, the namespaced syntax should not require `map` and use lifting instead:
`Config("aws").map(_.get("region"))` -> `Config("aws").get("region")`

Also default values like this:
```typescript
config.getNumber("replicas") || 2,
```
are currently impossible

### LINKED ISSUE #205: `config.getSecret` shorthand config key name is broken
The shorthand config key name is broken for secrets, this returns empty output:
`val mySecret = config.getSecret("mySecret")`

and when the key has the explicit namespace it works as expected:
`val mySecret = config.getSecret("aws-secrets-manager:mySecret")`

Relates to #204

### PR DESCRIPTION
**Pull request by pawelprazak**
- finishing touches on #287 to improve `Config` ergonomy
- add `Output[Option[A]].orElse` and `.getOrElse`
- add unit tests, integration tests, scaladoc

Fixes #204
Fixes #205

### CODE REVIEW

File: core/src/main/scala/besom/internal/Output.scala [hunk 1]
```diff
@@ -77,15 +77,22 @@ trait OutputFactory:
...
   def fail(t: Throwable)(using Context): Output[Nothing] = Output.fail(t)
 trait OutputExtensionsFactory:
   implicit final class OutputSequenceOps[A, CC[X] <: IterableOnce[X], To](coll: CC[Output[A]]):
     def sequence(using BuildFrom[CC[Output[A]], A, To], Context): Output[To] =
       Output.sequence(coll)
   implicit final class OutputTraverseOps[A, CC[X] <: IterableOnce[X]](coll: CC[A]):
     def traverse[B, To](f: A => Output[B])(using BuildFrom[CC[Output[B]], B, To], Context): Output[To] =
-      coll.map(f).asInstanceOf[CC[Output[B]]].sequence
+      coll.iterator.map(f).asInstanceOf[CC[Output[B]]].sequence
+  implicit final class OutputOptionOps[A](output: Output[Option[A]]):
```
Comment (pawelprazak) [inline core/src/main/scala/besom/internal/Output.scala:91]: @lbialy please have a look if those two methods make sense in this context

Comment (prolativ) [reply core/src/main/scala/besom/internal/Output.scala:91]: Is there any specific reason why implicit classes are used here instead of scala 3 extension methods?

File: core/src/main/scala/besom/internal/Output.scala [hunk 2]
```diff
@@ -77,15 +77,22 @@ trait OutputFactory:
...
+    def getOrElse[B >: A](default: => B)(using Context): Output[B] =
```
Comment (prolativ) [inline core/src/main/scala/besom/internal/Output.scala:92]: IMO it would be nice if a user could also pass values wrapped in `Output` as an argument as well
```suggestion
    def getOrElse[B >: A](default: => B | Output[B])(using Context): Output[B] =
```

File: core/src/main/scala/besom/internal/Output.scala [hunk 3]
```diff
@@ -77,15 +77,22 @@ trait OutputFactory:
...
+      output.flatMap(_.fold(Output(default))(Output(_)))
+    def orElse[B >: A](alternative: => Option[B]): Output[Option[B]] =
```
Comment (prolativ) [inline core/src/main/scala/besom/internal/Output.scala:94]: Maybe
```suggestion
    def orElse[B >: A](alternative: => Option[B] | Output[Option[B]]): Output[Option[B]] =
```?

File: core/src/main/scala/besom/util/NonEmptyString.scala [hunk 4]
```diff
@@ -3,20 +3,42 @@ package besom.util
...
+
+  /** @param s
+   * a [[String]] to be converted to a [[NonEmptyString]].
+   * @return
+   * a [[NonEmptyString]] if the given [[String]] is not empty or blank.
+   */
   inline def from(inline s: String): NonEmptyString = ${ fromImpl('s) }
 
-  def fromImpl(expr: Expr[String])(using quotes: Quotes): Expr[NonEmptyString] =
+  private def fromImpl(expr: Expr[String])(using quotes: Quotes): Expr[NonEmptyString] =
```
Comment (pawelprazak) [inline core/src/main/scala/besom/util/NonEmptyString.scala:41]: I've assumed it was not intentionally exposed.

File: core/src/main/scala/besom/types.scala [hunk 5]
```diff
@@ -91,8 +150,15 @@ object types:
   object Label:
     def fromNameAndType(name: NonEmptyString, rt: ResourceType): Label = s"$name[$rt]"
 
+  /** URN is and automatically constructed globally unique identifier for the resource
```
Comment (pawelprazak) [inline core/src/main/scala/besom/types.scala:153]:
```suggestion
  /** URN is an automatically constructed globally unique identifier for the resource
```

File: core/src/main/scala/besom/internal/BesomModule.scala [hunk 6]
```diff
@@ -3,40 +3,62 @@ package besom.internal
...
-        _              <- BesomLogger.setupLogger()
-        runInfo        <- RunInfo.fromEnv
-        _              <- logger.debug(s"Besom starting up in ${if runInfo.dryRun then "dry run" else "live"} mode.")
-        taskTracker    <- TaskTracker()
-        monitor        <- Result.resource(Monitor(runInfo.monitorAddress))(_.close())
-        engine         <- Result.resource(Engine(runInfo.engineAddress))(_.close())
-        _              <- logger.debug(s"Established connections to monitor and engine, spawning streaming pulumi logger.")
-        logger         <- Result.resource(BesomLogger(engine, taskTracker))(_.close())
-        config         <- Config.forProject(runInfo.project)
+        _           <- BesomLogger.setupLogger()
```
Comment (pawelprazak) [inline core/src/main/scala/besom/internal/BesomModule.scala:28]: don't know why `scalafmt` decided to change this

File: core/src/main/scala/besom/internal/Output.scala (hunk 1 above)
Comment (pawelprazak) [reply core/src/main/scala/besom/internal/Output.scala:91]: I've just followed the file's style, but actually was surprised as well, CC @lbialy

File: core/src/main/scala/besom/types.scala [hunk 7]
```diff
@@ -68,20 +116,31 @@ object types:
...
+      *   a function token string to parse
+      * @return
+      *   a [[FunctionToken]] if the string is valid, otherwise an compile time error occurs
+      */
     // validate that function token contains two colons between three identifiers, see @ResourceType
     inline def from(s: String): FunctionToken =
       requireConst(s)
-      inline if !constValue[Matches[s.type, ".+:.+:.+"]] then
-        error("Invalid function token")
+      inline if !constValue[Matches[s.type, ".+:.+:.+"]] then error("Invalid function token")
```
Comment (pawelprazak) [inline core/src/main/scala/besom/types.scala:135]: `scalafmt` insisted on this formating

File: core/src/main/scala/besom/internal/Output.scala (hunk 3 above)
Comment (prolativ) [reply core/src/main/scala/besom/internal/Output.scala]: Actually `Option[B] | Output[Option[B]]` could be written more shortly as `Input[Option[B]]`. The question is whether we would like to constrain the usage of `Input` to `Args` classes or not

File: core/src/main/scala/besom/internal/Output.scala (hunk 2 above)
Comment (pawelprazak) [reply core/src/main/scala/besom/internal/Output.scala]: reimplemented according to the suggestion

File: core/src/main/scala/besom/internal/Output.scala (hunk 3 above)
Comment (pawelprazak) [reply core/src/main/scala/besom/internal/Output.scala]: reimplemented according to the suggestion

File: core/src/main/scala/besom/internal/BesomModule.scala (hunk 6 above)
Comment (lbialy) [reply core/src/main/scala/besom/internal/BesomModule.scala:28]: maxColumns=120, should be 140, set maxColumns=140, reformat it back to how it was, don't check in change in .scalafmt.conf into this commit, just revert the reformatting here, we have to fix this in one go everywhere but let's not break our blame needlessly because we'll mark the reformatting commit as blame-transparent for git later

File: core/src/main/scala/besom/internal/Output.scala (hunk 1 above)
Comment (lbialy) [reply core/src/main/scala/besom/internal/Output.scala:91]: @KacperFKorban had a good reason for `implicit class` here, I think it was related to `import x.*` vs `import x.{*, given}` but that doesn't sound correct in regard to extension methods? Kacper, could you weigh in?

File: core/src/main/scala/besom/types.scala (hunk 7 above)
Comment (lbialy) [reply core/src/main/scala/besom/types.scala:135]: artifact from maxColumns=100 time I think, it's fine

File: core/src/main/scala/besom/util/NonEmptyString.scala (hunk 4 above)
Comment (lbialy) [reply core/src/main/scala/besom/util/NonEmptyString.scala:41]: good assumption

File: core/src/main/scala/besom/internal/Output.scala (hunk 1 above)
Comment (KacperFKorban) [reply core/src/main/scala/besom/internal/Output.scala:91]: This issue is in fact about extension methods.

The thing is that we don't just want to use `extension` methods. That's because extension methods can also be called as regular methods and this litters the scope, since in some cases we only want it to be an extension. That's why a true extension only method is defined as a given with that extension method inside e.g.:
```
given AnyRef with
  extension (i: Int)
    def foo = i + 1
```

This goes back to needing to do `import x.given` in addition to the usual `import x.*`.

**Comment by lbialy** [comment]
Ah, yeah. And an implicit class is given with extension but without given.

File: core/src/main/scala/besom/future.scala [hunk 8]
```diff
@@ -11,5 +14,22 @@ trait FutureMonadModule extends BesomModule:
   implicit val toFutureFuture: Result.ToFuture[Eff] = new Result.ToFuture[Future]:
     def eval[A](fa: => Future[A]): () => Future[A] = () => fa
 
+/**
+ * Besom API entry point for the [[scala.concurrent.Future]] monad.
+ *
+ * Please see `run` and `exports` methods to get started.
+ * Other notable methods are `log` and `config`.
```
[the remark this answers is not in the document]
Comment (pawelprazak) [reply core/src/main/scala/besom/future.scala:21]: done

File: core/src/main/scala/besom/internal/Output.scala [hunk 9]
```diff
@@ -77,15 +77,26 @@ trait OutputFactory:
...
     def sequence(using BuildFrom[CC[Output[A]], A, To], Context): Output[To] =
       Output.sequence(coll)
   implicit final class OutputTraverseOps[A, CC[X] <: IterableOnce[X]](coll: CC[A]):
     def traverse[B, To](f: A => Output[B])(using BuildFrom[CC[Output[B]], B, To], Context): Output[To] =
-      coll.map(f).asInstanceOf[CC[Output[B]]].sequence
+      coll.iterator.map(f).asInstanceOf[CC[Output[B]]].sequence
+  implicit final class OutputOptionOps[A](output: Output[Option[A]]):
+    def getOrElse[B >: A](default: => B | Output[B]): Output[B] =
+      default match
+        case b: Output[B] => for o <- output; b <- b yield o.getOrElse(b)
```
[the remark this answers is not in the document]
Comment (pawelprazak) [reply core/src/main/scala/besom/internal/Output.scala:94]: done

File: core/src/main/scala/besom/internal/Output.scala [hunk 10]
```diff
@@ -77,15 +77,26 @@ trait OutputFactory:
...
+        case b: B         => for o <- output yield o.getOrElse(b)
+    def orElse[B >: A](alternative: => Option[B] | Output[Option[B]]): Output[Option[B]] =
+      alternative match
+        case a: Output[Option[B]] => for o <- output; a <- a yield o.orElse(a)
+        case a: Option[B]         => for o <- output yield o.orElse(a)
```
[the remark this answers is not in the document]
Comment (pawelprazak) [reply core/src/main/scala/besom/internal/Output.scala:99]: done

**Comment by pawelprazak** [comment]
addressed the comments, added `ConfigError` and cleaned up Config factory methods from `throws`

File: core/src/main/scala/besom/future.scala [hunk 11]
```diff
@@ -3,13 +3,40 @@ package besom
...
 
+/** Besom API entry point for the [[scala.concurrent.Future]] monad.
+  *
+  * All Pulumi programs are executed in Besom context [[besom.Context]]
+  *
+  * Most notable methods exposed by [[besom.Pulumi]] are:
+  *   - [[besom.internal.BesomModule.run]] - the Pulumi program function
+  *   - [[besom.internal.BesomSyntax.exports]] - the Pulumi Stack outputs
+  *   - [[besom.internal.BesomSyntax.config]] - configuration and secrets
+  *   - [[besom.internal.BesomSyntax.log]] - all you logging needs
```
Comment (lbialy) [inline core/src/main/scala/besom/future.scala:24]: typo xD `you` -> `your`

File: core/src/main/scala/besom/internal/BesomModule.scala [hunk 12]
```diff
@@ -3,30 +3,63 @@ package besom.internal
...
         featureSupport <- FeatureSupport(monitor)
-        _              <- logger.trace(s"Environment:\n${sys.env.toSeq.sortBy(_._1).map((k, v) => s"$k: $v").mkString("\n")}")
-        _              <- logger.debug(s"Resolved feature support, spawning context and executing user program.")
-        ctx            <- Context(runInfo, taskTracker, monitor, engine, logger, featureSupport, config)
-        userOutputs    <- program(using ctx).map(_.toResult).getValueOrElse(Result.pure(Struct()))
-        _              <- Stack.registerStackOutputs(runInfo, userOutputs)(using ctx)
-        _              <- ctx.waitForAllTasks
+        _   <- logger.trace(s"Environment:\n${sys.env.toSeq.sortBy(_._1).map((k, v) => s"$k: $v").mkString("\n")}")
+        _   <- logger.debug(s"Resolved feature support, spawning context and executing user program.")
+        ctx <- Context(runInfo, taskTracker, monitor, engine, logger, featureSupport, config)
```
Comment (lbialy) [inline core/src/main/scala/besom/internal/BesomModule.scala:59]: why are these 3 lines indented this way? could you set maxColumns to 140 and reformat? I know it's asinine of me to demand ascii graphics in code but I really want to avoid dumb changes in the single reformat commit.

**Review by lbialy — CHANGES_REQUESTED** [review]

File: core/src/main/scala/besom/future.scala (hunk 11 above)
Comment (pawelprazak) [reply core/src/main/scala/besom/future.scala:24]:
```suggestion
  *   - [[besom.internal.BesomSyntax.log]] - all your logging needs
```

**Review by lbialy — APPROVED** [review]
